  adventureworks:
    target: dbt-demo
    outputs:
      dbt-demo:
        type: sqlserver # or synapse or whatever you want
        driver: "ODBC Driver 17 for SQL Server"
        server: "{{ env_var('SERVER') }}" 
        schema: "{{ env_var('SCHEMA') }}"
        database: "{{ env_var('DB') }}"
        authentication: CLI 
        port: 1433
        encrypt: true # adds "Encrypt=Yes" to connection string
        trust_cert: false

