adventureworks:
  target: dbt-demo
  outputs:
    dbt-demo:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: "{{ env_var('SERVER') }}"
      schema: "{{ env_var('SCHEMA') }}"
      database: "{{ env_var('DB') }}"
      authentication: CLI
      port: 1433
      encrypt: true
      trust_cert: false