# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, $(NAME)!
  displayName: 'Run a one-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: sudo apt-get install unixodbc-dev
  displayName: 'odbc driver'

- script: |
    python -m pip install --upgrade pip==20.1 setuptools>=40.1.0 wheel
    python -m pip install dbt-sqlserver
  displayName: 'dbt-sqlserver install'

- task: AzureCLI@2
  displayName: 'dbt debug'
  inputs:
    azureSubscription: sp-devops-demo
    ScriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd adventureworks
      dbt --version
      dbt debug

